services: 
 redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - reseau_docker  
  
  celery:
    build: .
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./uploads:/app/uploads
    environment:
      - CELERY_BROKER_URL=amqp://z28SN5429pup5xwC:pLm83EcfbnI76Ktpz-yke9QmZp4ScyjL@autorack.proxy.rlwy.net:16856/%2F
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Asia/Gaza
      - SAVE_DIRECTORY=/app/uploader
    command: celery -A app.celery worker --loglevel=info 
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '4'
          memory: 4G
  

  flask:
    build: .
    ports:
      - '5000:5000'
    environment:
      - CELERY_BROKER_URL=amqp://z28SN5429pup5xwC:pLm83EcfbnI76Ktpz-yke9QmZp4ScyjL@autorack.proxy.rlwy.net:16856/%2F
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:yxhPmwwwpisNQMfWGUeHTlEkdWDRSkLp@junction.proxy.rlwy.net:32235/railway
      - TZ=Asia/Gaza
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./uploads:/app/uploads 
  

      
 
