services: 
    
  celery:
    build: .
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./uploads:/app/uploads
    environment:
      - CELERY_BROKER_URL=amqp://2R6JhbKKsyxi3tn8:SaYu-e~EGDFbBbTP3BVO-YXjqfefNQJr@junction.proxy.rlwy.net:41673/%2F
      - CELERY_RESULT_BACKEND=redis://default:junction.proxy.rlwy.net:16188/0
      - TZ=Asia/Gaza
      - SAVE_DIRECTORY=/app/uploader
    command: celery -A app.celery worker --loglevel=info"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '4'
          memory: 4G

  

  flask:
    build: .
    ports:
      - '5000:5000'
    environment:
      - CELERY_BROKER_URL=amqp://2R6JhbKKsyxi3tn8:SaYu-e~EGDFbBbTP3BVO-YXjqfefNQJr@junction.proxy.rlwy.net:41673/%2F
      - CELERY_RESULT_BACKEND=redis://default:junction.proxy.rlwy.net:16188/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:yxhPmwwwpisNQMfWGUeHTlEkdWDRSkLp@junction.proxy.rlwy.net:32235/railway
      - TZ=Asia/Gaza
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./uploads:/app/uploads 


      
 
